document.addEventListener('DOMContentLoaded', () => {
    // Define the JSON data directly in JavaScript
    const posts = [
      {
        id: 1,
        title: "The Importance of Skincare Routine",
        author: "Jane Doe",
        content:  "<h2>Introduction</h2><p>Taking care of your skin is essential for maintaining a healthy and youthful appearance. A consistent skincare routine can help prevent various skin issues and improve the overall texture and tone of your skin.</p><h2>1. Removing Dead Skin Cells</h2><p>Exfoliation is a crucial step in any skincare routine. It helps to remove dead skin cells that can clog pores and lead to acne breakouts. Regular exfoliation promotes cell turnover, leaving your skin looking fresh and radiant.</p><h2>2. Preventing Acne and Breakouts</h2><p>A well-structured skincare routine can help keep acne at bay. Cleansing your skin twice a day removes dirt, oil, and impurities that can cause breakouts. Using products with ingredients like salicylic acid or benzoyl peroxide can further help in preventing and treating acne.</p><h2>3. Keeping Your Skin Hydrated</h2><p>Hydration is key to healthy skin. Using a good moisturizer helps to lock in moisture and maintain the skin's natural barrier. Hydrated skin looks plumper and more youthful, reducing the appearance of fine lines and wrinkles.</p><h2>4. Protecting Against Sun Damage</h2><p>Sun exposure is one of the leading causes of premature aging. Incorporating sunscreen into your daily skincare routine can protect your skin from harmful UV rays. Look for a broad-spectrum sunscreen with an SPF of at least 30.</p><h2>5. Enhancing Skin's Natural Glow</h2><p>A regular skincare routine that includes cleansing, toning, and moisturizing can enhance your skin's natural glow. Consistency is key to achieving and maintaining healthy, glowing skin.</p><h2>Conclusion</h2><p>Investing time and effort into a proper skincare routine can yield significant benefits for your skin's health and appearance. By following these steps, you can keep your skin looking its best and prevent various skin issues.</p>"
      },
      {
        id: 2,
        title: "Top 5 Skincare Tips for Glowing Skin",
        author: "John Smith",
        content: "<h2>Introduction</h2><p>Achieving glowing skin is not just about genetics—it's about establishing and maintaining a proper skincare routine. Glowing skin reflects good health and self-care, and with the right steps, anyone can achieve it.</p><h2>1. Stay Hydrated</h2><p>Hydration is the foundation of glowing skin. Drinking plenty of water helps to flush out toxins and keep your skin hydrated from the inside out. Proper hydration ensures that your skin remains plump and reduces the appearance of fine lines and wrinkles.</p><h2>2. Cleanse Regularly</h2><p>Cleansing your skin daily is crucial to remove dirt, oil, and impurities that accumulate throughout the day. Use a gentle cleanser that suits your skin type to avoid stripping your skin of its natural oils.</p><h2>3. Exfoliate to Remove Dead Skin Cells</h2><p>Exfoliation is key to achieving a radiant complexion. By removing dead skin cells, you allow new, fresh skin to surface, giving your skin a brighter and more even tone. Use a mild exfoliant 2-3 times a week to keep your skin smooth and glowing.</p><h2>4. Moisturize and Lock in Hydration</h2><p>Moisturizing is essential to maintain the skin's moisture barrier. A good moisturizer helps to lock in hydration, keeping your skin soft and supple. Choose a moisturizer that suits your skin type, whether it’s oily, dry, or combination skin.</p><h2>5. Use Sunscreen Daily</h2><p>Sun damage is one of the primary causes of dull and uneven skin. Applying sunscreen daily protects your skin from harmful UV rays, preventing premature aging, dark spots, and skin cancer. Opt for a broad-spectrum sunscreen with an SPF of 30 or higher.</p><h2>6. Incorporate Antioxidants</h2><p>Antioxidants, such as vitamin C, play a crucial role in achieving glowing skin. They help to fight free radicals, reduce inflammation, and promote collagen production. Incorporating a vitamin C serum into your routine can brighten your skin and reduce signs of aging.</p><h2>Conclusion</h2><p>Achieving glowing skin requires a consistent and well-rounded skincare routine. By following these steps—hydration, cleansing, exfoliating, moisturizing, using sunscreen, and incorporating antioxidants—you can enhance your skin’s natural glow and maintain a healthy complexion.</p>"
      },
      {
        id: 3,
        title: "Natural Skincare Remedies",
        author: "Alice Johnson",
        content: "<h2>Introduction</h2><p>Natural skincare remedies have been used for centuries to maintain healthy and glowing skin. These remedies, often derived from plants and other natural sources, offer a chemical-free alternative to commercial skincare products. Incorporating these remedies into your routine can help nourish, protect, and rejuvenate your skin.</p><h2>1. Honey for Hydration</h2><p>Honey is a natural humectant, meaning it draws moisture into the skin. It's also packed with antioxidants that help to repair and protect the skin from damage. Applying raw honey to your face as a mask for 15-20 minutes can leave your skin feeling soft, hydrated, and glowing.</p><h2>2. Aloe Vera for Soothing</h2><p>Aloe vera is known for its soothing and healing properties. It’s especially effective in treating sunburns, irritation, and minor cuts. The gel from an aloe vera plant can be applied directly to the skin to reduce redness and inflammation while promoting healing.</p><h2>3. Coconut Oil for Moisturizing</h2><p>Coconut oil is rich in fatty acids that deeply moisturize and nourish the skin. It’s particularly beneficial for dry skin, providing a protective barrier that locks in moisture. Apply a small amount of coconut oil to your skin after cleansing to keep it soft and smooth.</p><h2>4. Green Tea for Anti-Aging</h2><p>Green tea is packed with antioxidants that can help combat the signs of aging. Its anti-inflammatory properties also make it a great remedy for reducing puffiness and soothing irritated skin. You can use cooled green tea bags as a compress for your eyes or apply green tea extract as a toner.</p><h2>5. Turmeric for Brightening</h2><p>Turmeric has been used in skincare for its brightening and anti-inflammatory properties. A turmeric mask can help even out skin tone and reduce the appearance of dark spots. Mix turmeric with yogurt or honey to create a mask, leave it on for about 10 minutes, and then rinse off to reveal glowing skin.</p><h2>6. Oatmeal for Exfoliation</h2><p>Oatmeal is a gentle exfoliant that can help remove dead skin cells and unclog pores. It also has anti-inflammatory properties that soothe irritated skin. Mix ground oatmeal with water or yogurt to create a paste, apply it to your face, and gently massage in circular motions before rinsing off.</p><h2>Conclusion</h2><p>Natural skincare remedies offer a safe and effective way to care for your skin. By incorporating ingredients like honey, aloe vera, coconut oil, green tea, turmeric, and oatmeal into your routine, you can enhance your skin's health and appearance without relying on harsh chemicals. These remedies are not only beneficial but also easy to find and use at home.</p>"
      }
    ];
  
    // Get the blog container element
    const blogContainer = document.getElementById('blog-container');
  
    // Loop through the posts and create HTML for each post
    posts.forEach(post => {
      const postElement = document.createElement('div');
      postElement.classList.add('blog-post');
      postElement.innerHTML = `
        <h2>${post.title}</h2>
        <p><strong>Author:</strong> ${post.author}</p>
        <p>${post.content}</p>
      `;
      // Append the post element to the blog container
      blogContainer.appendChild(postElement);
    });
  });
  